
flemmarr:
  server:
    address: jellyseerr # Assuming Flemmarr and Jellyseerr are on same network
    port: 5055
  config:
    main:
      apiKey: '${API_KEY}'
      applicationTitle: Jellyseerr
      applicationUrl: ''
      csrfProtection: false
      cacheImages: false
      defaultPermissions: 32
      defaultQuotas:
        movie: {}
        tv: {}
      hideAvailable: false
      localLogin: true
      newPlexLogin: true
      region: ''
      originalLanguage: ''
      trustProxy: false
      mediaServerType: 2  # 2 for Jellyfin, change to 1 for Plex
      partialRequestsEnabled: true
      locale: en
    jellyfin:
      name: '03d2cfc9d417'
      hostname: 'http://10.0.0.50:8096'
      externalHostname: '' # Use if Jellyfin is behind a reverse proxy
      jellyfinForgotPasswordUrl: ''
      libraries:
        - id: 'f137a2dd21bbc1b99aa5c0f6bf02a805'
          name: Movies
          enabled: true
          type: movie
        - id: 'a656b907eb3a73532e40e44b968d0225'
          name: Shows
          enabled: true
          type: show
      serverId: '60ed8511de3546188fbbd11126352acc'
    radarr:
      - name: radarr
        hostname: '10.0.0.50'
        port: 7878
        apiKey: '${RADARR_API_KEY}'
        useSsl: false
        baseUrl: ''
        activeProfileId: 6
        activeProfileName: 'HD - 720p/1080p'
        activeDirectory: '/movies'
        is4k: false
        minimumAvailability: inCinemas
        tags: []
        isDefault: true
        syncEnabled: true
        preventSearch: false
        tagRequests: false
        id: 0
    sonarr:
      - name: sonarr
        hostname: '10.0.0.50'  # Assuming Sonarr is on the same Docker network
        port: 8989
        apiKey: '${SONARR_API_KEY}'
        useSsl: false
        baseUrl: ''
        activeProfileId: 6
        activeLanguageProfileId: 1
        activeProfileName: 'HD - 720p/1080p'
        activeDirectory: '/tv'
        animeSeriesType: anime
        activeAnimeProfileId: 6
        activeAnimeLanguageProfileId: 1
        activeAnimeProfileName: 'HD - 720p/1080p'
        activeAnimeDirectory: '/tv'
        tags: []
        animeTags: []
        is4k: false
        isDefault: true
        enableSeasonFolders: true
        syncEnabled: true
        preventSearch: false
        tagRequests: false
        id: 0
    lidarr:
      BindAddress: '*'
      Port: 8686
      SslPort: 6868
      EnableSsl: false
      LaunchBrowser: true
      ApiKey: '${LIDARR_API_KEY}'
      AuthenticationMethod: Forms
      AuthenticationRequired: DisabledForLocalAddresses
      Branch: master
      LogLevel: info
      SslCertPath: ''
      SslCertPassword: ''
      UrlBase: ''
      InstanceName: Lidarr
      UpdateMechanism: Docker
    prowlarr:
      BindAddress: '*'
      Port: 9696
      SslPort: 6969
      EnableSsl: false
      LaunchBrowser: true
      ApiKey: '${PROWLARR_API_KEY}'
      AuthenticationMethod: Forms
      AuthenticationRequired: DisabledForLocalAddresses
      Branch: master
      LogLevel: info
      SslCertPath: ''
      SslCertPassword: ''
      UrlBase: ''
      InstanceName: Prowlarr
      UpdateMechanism: Docker
    qbittorrent:
      Application:
        FileLogger\Age: 1
        FileLogger\AgeType: 1
        FileLogger\Backup: true
        FileLogger\DeleteOld: true
        FileLogger\Enabled: true
        FileLogger\MaxSizeBytes: 66560
        FileLogger\Path: /config/qBittorrent/logs
        MemoryWorkingSetLimit: 2000
      AutoRun:
        enabled: false
        program: ''
      BitTorrent:
        Session\AlternativeGlobalDLSpeedLimit: 10000
        Session\AlternativeGlobalUPSpeedLimit: 10000
        Session\AnonymousModeEnabled: true
        Session\BandwidthSchedulerEnabled: true
        Session\DefaultSavePath: /downloads/
        Session\DisableAutoTMMByDefault: false
        Session\Encryption: 1
        Session\ExcludedFileNames: ''
        Session\GlobalDLSpeedLimit: 25000
        Session\GlobalMaxInactiveSeedingMinutes: 1440
        Session\GlobalUPSpeedLimit: 50000
        Session\IgnoreSlowTorrentsForQueueing: true
        Session\IncludeOverheadInLimits: true
        Session\Interface: tun0 # You might need to adjust this based on your VPN setup
        Session\InterfaceAddress: '0.0.0.0'
        Session\InterfaceName: tun0
        Session\MaxActiveCheckingTorrents: 2
        Session\MaxActiveDownloads: 10
        Session\MaxActiveTorrents: 20
        Session\MaxActiveUploads: 10
        Session\Port: 6881
        Session\Preallocation: true
        Session\QueueingSystemEnabled: true
        Session\SlowTorrentsDownloadRate: 500
        Session\SlowTorrentsUploadRate: 500
        Session\TempPath: /downloads/incomplete/
        Session\UseAlternativeGlobalSpeedLimit: false
      Core:
        AutoDeleteAddedTorrentFile: Never
      LegalNotice:
        Accepted: true
      Meta:
        MigrationVersion: 6
      Network:
        PortForwardingEnabled: true
        Proxy\HostnameLookupEnabled: false
        Proxy\Profiles\BitTorrent: true
        Proxy\Profiles\Misc: true
        Proxy\Profiles\RSS: true
      Preferences:
        Advanced\RecheckOnCompletion: true
        Connection\PortRangeMin: 6881
        Connection\UPnP: false
        Downloads\SavePath: /downloads/
        Downloads\TempPath: /downloads/incomplete/
        General\Locale: en
        # ... (Other Preferences settings - sanitize sensitive data)
      RSS:
        AutoDownloader\DownloadRepacks: true
        AutoDownloader\SmartEpisodeFilter: 's(\\d+)e(\\d+), (\\d+)x(\\d+), "(\\d{4}[.\\-]\\d{1,2}[.\\-]\\d{1,2})", "(\\d{1,2}[.\\-]\\d{1,2}[.\\-]\\d{4})"'
    bazarr:
      branch: master
      chmod: '0640'
      chmod_enabled: false
      days_to_upgrade_subs: 7
      debug: false
      default_und_audio_lang: ''
      default_und_embedded_subtitles_lang: ''
      dont_notify_manual_actions: false
      embedded_subs_show_desired: true
      embedded_subtitles_parser: ffprobe
      enabled_integrations: []
      enabled_providers: []
      flask_secret_key: 'UPDATE_THIS_WITH_A_NEW_SECRET_KEY'
      hi_extension: hi
      ignore_ass_subs: false
      ignore_pgs_subs: false
      ignore_vobsub_subs: false
      ip: '0.0.0.0'
      language_equals: []
      minimum_score: 90
      minimum_score_movie: 70
      movie_default_enabled: false
      movie_default_profile: ''
      multithreading: true
      page_size: 25
      parse_embedded_audio_track: false
      path_mappings: []
      path_mappings_movie: []
      port: 6767 # You might need to change this if it conflicts
      postprocessing_cmd: ''
      postprocessing_threshold: 90
      postprocessing_threshold_movie: 70
      serie_default_enabled: false
      serie_default_profile: ''
      single_language: false
      skip_hashing: false
      subfolder: current
      subfolder_custom: ''
      subzero_mods: ''
      theme: auto
      upgrade_frequency: 12
      upgrade_manual: true
      upgrade_subs: true
      use_embedded_subs: true
      use_postprocessing: false
      use_postprocessing_threshold: false
      use_postprocessing_threshold_movie: false
      use_radarr: false
      use_scenename: true
      use_sonarr: false
      utf8_encode: true
      wanted_search_frequency: 6
      wanted_search_frequency_movie: 6
